// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by scripts/generate_rest_tests.py; DO NOT EDIT.
// Regenerate with:  python3 scripts/generate_rest_tests.py
//
// Full-mock REST wire-tests for the 'datasphere' namespace (item E). One SUCCESS +
// one ERROR test per implemented canonical route. The call literal is captured
// verbatim from the real generated client by tools/route_registry.cpp; the
// asserted matched_route is the OpenAPI operationId resolved by the mock's own
// SpecLoader — an oracle INDEPENDENT of the resource generator. Included by
// tests/test_main.cpp.
#include "mocktest.hpp"

namespace {
using namespace signalwire::rest;
using nlohmann::json;
}  // namespace

TEST(rest_mock_gen_datasphere_documents_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.delete_document", 200, json::object());
  (void)(client.datasphere().documents.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.delete_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.delete_document", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.delete_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_deletechunk_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.delete_document_chunk", 200, json::object());
  (void)(client.datasphere().documents.delete_chunk("X", "X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.delete_document_chunk"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_deletechunk_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.delete_document_chunk", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.delete_chunk("X", "X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.delete_document_chunk"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.list_documents", 200, json::object());
  (void)(client.datasphere().documents.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.list_documents"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.list_documents", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.list_documents"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.get_document", 200, json::object());
  (void)(client.datasphere().documents.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.get_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.get_document", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.get_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_listchunks_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.list_document_chunks", 200, json::object());
  (void)(client.datasphere().documents.list_chunks("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.list_document_chunks"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_listchunks_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.list_document_chunks", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.list_chunks("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.list_document_chunks"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_getchunk_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.get_document_chunk", 200, json::object());
  (void)(client.datasphere().documents.get_chunk("X", "X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.get_document_chunk"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_getchunk_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.get_document_chunk", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.get_chunk("X", "X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.get_document_chunk"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.update_document", 200, json::object());
  (void)(client.datasphere().documents.update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PATCH"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.update_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.update_document", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.update_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.create_document", 200, json::object());
  (void)(client.datasphere().documents.create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.create_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.create_document", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.create_document"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_search_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.search_documents", 200, json::object());
  (void)(client.datasphere().documents.search({.query_string = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.search_documents"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_datasphere_documents_search_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("datasphere.search_documents", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.datasphere().documents.search({.query_string = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("datasphere.search_documents"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}
