// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by scripts/generate_rest_tests.py; DO NOT EDIT.
// Regenerate with:  python3 scripts/generate_rest_tests.py
//
// Full-mock REST wire-tests for the 'space' namespace (item E). One SUCCESS +
// one ERROR test per implemented canonical route. The call literal is captured
// verbatim from the real generated client by tools/route_registry.cpp; the
// asserted matched_route is the OpenAPI operationId resolved by the mock's own
// SpecLoader — an oracle INDEPENDENT of the resource generator. Included by
// tests/test_main.cpp.
#include "mocktest.hpp"

namespace {
using namespace signalwire::rest;
using nlohmann::json;
}  // namespace

TEST(rest_mock_gen_space_members_delete_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.delete_member", 200, json::object());
  (void)(client.space().members.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.delete_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_delete_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.delete_member", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.delete_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_disable_project_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.disable_member_project", 200, json::object());
  (void)(client.space().members.disable_project("X", "X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.disable_member_project"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_disable_project_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.disable_member_project", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.disable_project("X", "X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.disable_member_project"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_payment_methods_delete_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.delete_payment_method", 200, json::object());
  (void)(client.space().payment_methods.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.delete_payment_method"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_payment_methods_delete_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.delete_payment_method", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().payment_methods.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.delete_payment_method"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_settings_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_space", 200, json::object());
  (void)(client.space().settings.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_space"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_settings_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_space", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().settings.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_space"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_balance_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_balance", 200, json::object());
  (void)(client.space().balance.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_balance"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_balance_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_balance", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().balance.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_balance"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_profile_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_profile", 200, json::object());
  (void)(client.space().billing_profile.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_profile_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_profile", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().billing_profile.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_statement", 200, json::object());
  (void)(client.space().billing_statements.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_statement"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_statement", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().billing_statements.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_statement"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_get_csv_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_statement_csv", 200, json::object());
  (void)(client.space().billing_statements.get_csv(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_statement_csv"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_get_csv_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_statement_csv", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().billing_statements.get_csv(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_statement_csv"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_get_pdf_ok) {
  auto client = mocktest::make_pat_client();
  (void)(client.space().billing_statements.get_pdf(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_statement_pdf"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 300 && *j.response_status < 400);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_get_pdf_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_billing_statement_pdf", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().billing_statements.get_pdf(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_billing_statement_pdf"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_list_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_billing_statement_periods", 200, json::object());
  (void)(client.space().billing_statements.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_billing_statement_periods"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_statements_list_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_billing_statement_periods", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().billing_statements.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_billing_statement_periods"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_geographic_permissions_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_geographic_permissions", 200, json::object());
  (void)(client.space().geographic_permissions.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_geographic_permissions"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_geographic_permissions_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_geographic_permissions", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().geographic_permissions.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_geographic_permissions"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_low_balance_setting_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_low_balance_setting", 200, json::object());
  (void)(client.space().low_balance_setting.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_low_balance_setting"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_low_balance_setting_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_low_balance_setting", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().low_balance_setting.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_low_balance_setting"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_list_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_members", 200, json::object());
  (void)(client.space().members.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_members"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_list_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_members", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_members"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_member", 200, json::object());
  (void)(client.space().members.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_member", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_list_projects_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_member_projects", 200, json::object());
  (void)(client.space().members.list_projects("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_member_projects"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_list_projects_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_member_projects", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.list_projects("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_member_projects"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_payment_history_list_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_payment_history", 200, json::object());
  (void)(client.space().payment_history.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_payment_history"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_payment_history_list_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_payment_history", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().payment_history.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_payment_history"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_payment_methods_list_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_payment_methods", 200, json::object());
  (void)(client.space().payment_methods.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_payment_methods"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_payment_methods_list_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.list_payment_methods", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().payment_methods.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.list_payment_methods"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_usage_get_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_usage", 200, json::object());
  (void)(client.space().usage.get(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_usage"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_usage_get_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.get_usage", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().usage.get(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.get_usage"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_update_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_member", 200, json::object());
  (void)(client.space().members.update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PATCH"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_update_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_member", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_balance_create_top_up_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.create_top_up", 200, json::object());
  (void)(client.space().balance.create_top_up(
      {.idempotency_key = "X", .amount_in_microdollars = 1, .payment_method_id = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.create_top_up"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_balance_create_top_up_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.create_top_up", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().balance.create_top_up(
        {.idempotency_key = "X", .amount_in_microdollars = 1, .payment_method_id = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.create_top_up"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_create_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.create_member", 200, json::object());
  (void)(client.space().members.create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.create_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_create_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.create_member", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.create_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_settings_update_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_space", 200, json::object());
  (void)(client.space().settings.update({}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_space"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_settings_update_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_space", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().settings.update({}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_space"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_profile_update_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_billing_profile", 200, json::object());
  (void)(client.space().billing_profile.update({.address_line1 = "X",
                                                .address_city = "X",
                                                .address_state = "X",
                                                .address_zip = "X",
                                                .address_country = "X",
                                                .company_name = "X",
                                                .contact_name = "X",
                                                .contact_email = "X",
                                                .contact_phone = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_billing_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_billing_profile_update_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_billing_profile", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().billing_profile.update({.address_line1 = "X",
                                                  .address_city = "X",
                                                  .address_state = "X",
                                                  .address_zip = "X",
                                                  .address_country = "X",
                                                  .company_name = "X",
                                                  .contact_name = "X",
                                                  .contact_email = "X",
                                                  .contact_phone = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_billing_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_geographic_permissions_update_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_geographic_permissions", 200, json::object());
  (void)(client.space().geographic_permissions.update({.countries = json::array()}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_geographic_permissions"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_geographic_permissions_update_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_geographic_permissions", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().geographic_permissions.update({.countries = json::array()}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_geographic_permissions"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_low_balance_setting_update_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_low_balance_setting", 200, json::object());
  (void)(client.space().low_balance_setting.update({}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_low_balance_setting"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_low_balance_setting_update_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.update_low_balance_setting", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().low_balance_setting.update({}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.update_low_balance_setting"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_space_members_enable_project_ok) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.enable_member_project", 200, json::object());
  (void)(client.space().members.enable_project("X", "X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.enable_member_project"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_space_members_enable_project_err) {
  auto client = mocktest::make_pat_client();
  mocktest::scenario_set("space.enable_member_project", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.space().members.enable_project("X", "X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status_code();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("space.enable_member_project"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}
