// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by scripts/generate_rest_tests.py; DO NOT EDIT.
// Regenerate with:  python3 scripts/generate_rest_tests.py
//
// Full-mock REST wire-tests for the 'message' namespace (item E). One SUCCESS +
// one ERROR test per implemented canonical route. The call literal is captured
// verbatim from the real generated client by tools/route_registry.cpp; the
// asserted matched_route is the OpenAPI operationId resolved by the mock's own
// SpecLoader — an oracle INDEPENDENT of the resource generator. Included by
// tests/test_main.cpp.
#include "mocktest.hpp"

namespace {
using namespace signalwire::rest;
using nlohmann::json;
}  // namespace

TEST(rest_mock_gen_logs_messages_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("message.list_message_logs", 200, json::object());
  (void)(client.logs().messages.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("message.list_message_logs"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_logs_messages_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("message.list_message_logs", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.logs().messages.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("message.list_message_logs"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_logs_messages_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("message.get_message_log", 200, json::object());
  (void)(client.logs().messages.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("message.get_message_log"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_logs_messages_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("message.get_message_log", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.logs().messages.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("message.get_message_log"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}
