// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by scripts/generate_rest_tests.py; DO NOT EDIT.
// Regenerate with:  python3 scripts/generate_rest_tests.py
//
// Full-mock REST wire-tests for the 'relay-rest' namespace (item E). One SUCCESS +
// one ERROR test per implemented canonical route. The call literal is captured
// verbatim from the real generated client by tools/route_registry.cpp; the
// asserted matched_route is the OpenAPI operationId resolved by the mock's own
// SpecLoader — an oracle INDEPENDENT of the resource generator. Included by
// tests/test_main.cpp.
#include "mocktest.hpp"

namespace {
using namespace signalwire::rest;
using nlohmann::json;
}  // namespace

TEST(rest_mock_gen_addresses_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_address", 200, json::object());
  (void)(client.addresses().delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_address"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_addresses_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_address", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.addresses().delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_address"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_delete_membership_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_number_group_membership", 200, json::object());
  (void)(client.number_groups().delete_membership("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_number_group_membership"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_delete_membership_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_number_group_membership", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().delete_membership("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_number_group_membership"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_number_group", 200, json::object());
  (void)(client.number_groups().delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_number_group", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.release_phone_number", 200, json::object());
  (void)(client.phone_numbers().delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.release_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.release_phone_number", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.phone_numbers().delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.release_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_queue", 200, json::object());
  (void)(client.queues().delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_queue", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_recordings_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_recording", 200, json::object());
  (void)(client.recordings().delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_recordings_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_recording", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.recordings().delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_numbers_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_number_assignment", 200, json::object());
  (void)(client.registry().numbers.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_number_assignment"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_numbers_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_number_assignment", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().numbers.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_number_assignment"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_verified_caller_id", 200, json::object());
  (void)(client.verified_callers().delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.delete_verified_caller_id", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.delete_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_addresses_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_addresses", 200, json::object());
  (void)(client.addresses().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_addresses"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_addresses_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_addresses", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.addresses().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_addresses"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_addresses_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.get_address", 200, json::object());
  (void)(client.addresses().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.get_address"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_addresses_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.get_address", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.addresses().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.get_address"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_lookup_phone_number_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.lookup_phone_number", 200, json::object());
  (void)(client.lookup().phone_number("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.lookup_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_lookup_phone_number_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.lookup_phone_number", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.lookup().phone_number("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.lookup_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_get_membership_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_number_group_membership", 200, json::object());
  (void)(client.number_groups().get_membership("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_number_group_membership"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_get_membership_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_number_group_membership", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().get_membership("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_number_group_membership"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_number_groups", 200, json::object());
  (void)(client.number_groups().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_number_groups"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_number_groups", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_number_groups"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_number_group", 200, json::object());
  (void)(client.number_groups().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_number_group", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_list_memberships_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_number_group_memberships", 200, json::object());
  (void)(client.number_groups().list_memberships("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_number_group_memberships"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_list_memberships_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_number_group_memberships", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().list_memberships("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_number_group_memberships"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_phone_numbers", 200, json::object());
  (void)(client.phone_numbers().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_phone_numbers"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_phone_numbers", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.phone_numbers().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_phone_numbers"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_search_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.search_available_phone_numbers", 200, json::object());
  (void)(client.phone_numbers().search(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.search_available_phone_numbers"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_search_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.search_available_phone_numbers", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.phone_numbers().search(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.search_available_phone_numbers"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_phone_number", 200, json::object());
  (void)(client.phone_numbers().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_phone_number", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.phone_numbers().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_queues", 200, json::object());
  (void)(client.queues().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_queues"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_queues", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_queues"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.get_queue", 200, json::object());
  (void)(client.queues().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.get_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.get_queue", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.get_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_list_members_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_queue_members", 200, json::object());
  (void)(client.queues().list_members("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_queue_members"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_list_members_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_queue_members", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().list_members("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_queue_members"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_get_next_member_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_next_queue_member", 200, json::object());
  (void)(client.queues().get_next_member("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_next_queue_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_get_next_member_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_next_queue_member", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().get_next_member("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_next_queue_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_get_member_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_queue_member", 200, json::object());
  (void)(client.queues().get_member("X", "X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_queue_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_get_member_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_queue_member", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().get_member("X", "X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_queue_member"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_recordings_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_recordings", 200, json::object());
  (void)(client.recordings().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_recordings"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_recordings_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_recordings", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.recordings().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_recordings"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_recordings_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.get_recording", 200, json::object());
  (void)(client.recordings().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.get_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_recordings_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.get_recording", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.recordings().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.get_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_brands", 200, json::object());
  (void)(client.registry().brands.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_brands"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_brands", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().brands.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_brands"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_brand", 200, json::object());
  (void)(client.registry().brands.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_brand"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_brand", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().brands.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_brand"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_list_campaigns_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_campaigns", 200, json::object());
  (void)(client.registry().brands.list_campaigns("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_campaigns"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_list_campaigns_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_campaigns", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().brands.list_campaigns("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_campaigns"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_campaign", 200, json::object());
  (void)(client.registry().campaigns.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_campaign"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_campaign", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().campaigns.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_campaign"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_list_numbers_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_number_assignments", 200, json::object());
  (void)(client.registry().campaigns.list_numbers("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_number_assignments"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_list_numbers_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_number_assignments", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().campaigns.list_numbers("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_number_assignments"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_list_orders_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_orders", 200, json::object());
  (void)(client.registry().campaigns.list_orders("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_orders"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_list_orders_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_orders", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().campaigns.list_orders("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_orders"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_orders_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_order", 200, json::object());
  (void)(client.registry().orders.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_order"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_orders_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_order", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().orders.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_order"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_short_codes_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_short_codes", 200, json::object());
  (void)(client.short_codes().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_short_codes"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_short_codes_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_short_codes", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.short_codes().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_short_codes"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_short_codes_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_short_code", 200, json::object());
  (void)(client.short_codes().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_short_code"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_short_codes_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_short_code", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.short_codes().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_short_code"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_sip_profile_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_sip_profile", 200, json::object());
  (void)(client.sip_profile().get());
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_sip_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_sip_profile_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_sip_profile", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.sip_profile().get());
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_sip_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_verified_caller_ids", 200, json::object());
  (void)(client.verified_callers().list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_verified_caller_ids"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.list_verified_caller_ids", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.list_verified_caller_ids"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_verified_caller_id", 200, json::object());
  (void)(client.verified_callers().get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.retrieve_verified_caller_id", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.retrieve_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_addresses_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_address", 200, json::object());
  (void)(client.addresses().create({.label = "X", .country = "X", .first_name = "X", .last_name = "X", .street_number = "X", .street_name = "X", .city = "X", .state = "X", .postal_code = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_address"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_addresses_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_address", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.addresses().create({.label = "X", .country = "X", .first_name = "X", .last_name = "X", .street_number = "X", .street_name = "X", .city = "X", .state = "X", .postal_code = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_address"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_imported_numbers_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_imported_phone_number", 200, json::object());
  (void)(client.imported_numbers().create({.number = "X", .number_type = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_imported_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_imported_numbers_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_imported_phone_number", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.imported_numbers().create({.number = "X", .number_type = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_imported_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_mfa_call_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.request_mfa_call", 200, json::object());
  (void)(client.mfa().call({.to = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.request_mfa_call"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_mfa_call_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.request_mfa_call", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.mfa().call({.to = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.request_mfa_call"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_mfa_sms_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.request_mfa_sms", 200, json::object());
  (void)(client.mfa().sms({.to = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.request_mfa_sms"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_mfa_sms_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.request_mfa_sms", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.mfa().sms({.to = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.request_mfa_sms"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_mfa_verify_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.verify_mfa_token", 200, json::object());
  (void)(client.mfa().verify("X", {.token = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.verify_mfa_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_mfa_verify_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.verify_mfa_token", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.mfa().verify("X", {.token = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.verify_mfa_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_number_group", 200, json::object());
  (void)(client.number_groups().create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_number_group", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_add_membership_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_number_group_membership", 200, json::object());
  (void)(client.number_groups().add_membership("X", {.phone_number_id = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_number_group_membership"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_add_membership_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_number_group_membership", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().add_membership("X", {.phone_number_id = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_number_group_membership"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.purchase_phone_number", 200, json::object());
  (void)(client.phone_numbers().create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.purchase_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.purchase_phone_number", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.phone_numbers().create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.purchase_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_queue", 200, json::object());
  (void)(client.queues().create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_queue", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_brand", 200, json::object());
  (void)(client.registry().brands.create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_brand"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_brand", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().brands.create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_brand"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_create_campaign_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_campaign", 200, json::object());
  (void)(client.registry().brands.create_campaign("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_campaign"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_brands_create_campaign_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_campaign", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().brands.create_campaign("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_campaign"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_create_order_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_order", 200, json::object());
  (void)(client.registry().campaigns.create_order("X", {}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_order"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_create_order_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_order", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().campaigns.create_order("X", {}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_order"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_verified_caller_id", 200, json::object());
  (void)(client.verified_callers().create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.create_verified_caller_id", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.create_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_redial_verification_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.redial_verification_call", 200, json::object());
  (void)(client.verified_callers().redial_verification("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.redial_verification_call"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_redial_verification_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.redial_verification_call", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().redial_verification("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.redial_verification_call"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_number_group", 200, json::object());
  (void)(client.number_groups().update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_number_groups_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_number_group", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.number_groups().update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_number_group"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_phone_number", 200, json::object());
  (void)(client.phone_numbers().update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_phone_numbers_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_phone_number", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.phone_numbers().update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_phone_number"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_queues_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_queue", 200, json::object());
  (void)(client.queues().update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_queues_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_queue", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.queues().update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_queue"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_campaign", 200, json::object());
  (void)(client.registry().campaigns.update("X", {}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_campaign"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_registry_campaigns_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_campaign", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.registry().campaigns.update("X", {}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_campaign"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_short_codes_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_short_code", 200, json::object());
  (void)(client.short_codes().update("X", {.name = "X", .message_handler = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_short_code"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_short_codes_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_short_code", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.short_codes().update("X", {.name = "X", .message_handler = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_short_code"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_sip_profile_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_sip_profile", 200, json::object());
  (void)(client.sip_profile().update({}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_sip_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_sip_profile_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_sip_profile", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.sip_profile().update({}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_sip_profile"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_verified_caller_id", 200, json::object());
  (void)(client.verified_callers().update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.update_verified_caller_id", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.update_verified_caller_id"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_submit_verification_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.validate_verification_code", 200, json::object());
  (void)(client.verified_callers().submit_verification("X", {.verification_code = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.validate_verification_code"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_verified_callers_submit_verification_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("relay-rest.validate_verification_code", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.verified_callers().submit_verification("X", {.verification_code = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("relay-rest.validate_verification_code"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}
