// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by scripts/generate_rest_tests.py; DO NOT EDIT.
// Regenerate with:  python3 scripts/generate_rest_tests.py
//
// Full-mock REST wire-tests for the 'video' namespace (item E). One SUCCESS +
// one ERROR test per implemented canonical route. The call literal is captured
// verbatim from the real generated client by tools/route_registry.cpp; the
// asserted matched_route is the OpenAPI operationId resolved by the mock's own
// SpecLoader — an oracle INDEPENDENT of the resource generator. Included by
// tests/test_main.cpp.
#include "mocktest.hpp"

namespace {
using namespace signalwire::rest;
using nlohmann::json;
}  // namespace

TEST(rest_mock_gen_video_conferences_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_video_conference", 200, json::object());
  (void)(client.video().conferences.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_video_conference", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_room_recording", 200, json::object());
  (void)(client.video().room_recordings.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_room_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_room_recording", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_recordings.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_room_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_room", 200, json::object());
  (void)(client.video().rooms.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_room"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_room", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_room"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_streams_delete_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_stream", 200, json::object());
  (void)(client.video().streams.delete_("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("DELETE"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_streams_delete_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.delete_stream", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().streams.delete_("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.delete_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conference_tokens_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_conference_token", 200, json::object());
  (void)(client.video().conference_tokens.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_conference_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conference_tokens_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_conference_token", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conference_tokens.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_conference_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_video_conferences", 200, json::object());
  (void)(client.video().conferences.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_video_conferences"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_video_conferences", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_video_conferences"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_video_conference", 200, json::object());
  (void)(client.video().conferences.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_video_conference", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_listconferencetokens_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_conference_tokens", 200, json::object());
  (void)(client.video().conferences.list_conference_tokens("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_conference_tokens"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_listconferencetokens_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_conference_tokens", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.list_conference_tokens("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_conference_tokens"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_liststreams_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_conference_streams", 200, json::object());
  (void)(client.video().conferences.list_streams("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_conference_streams"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_liststreams_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_conference_streams", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.list_streams("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_conference_streams"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_recordings", 200, json::object());
  (void)(client.video().room_recordings.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_recordings"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_recordings", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_recordings.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_recordings"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_room_recording", 200, json::object());
  (void)(client.video().room_recordings.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_room_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_room_recording", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_recordings.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_room_recording"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_listevents_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_recording_events", 200, json::object());
  (void)(client.video().room_recordings.list_events("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_recording_events"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_recordings_listevents_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_recording_events", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_recordings.list_events("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_recording_events"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_sessions", 200, json::object());
  (void)(client.video().room_sessions.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_sessions"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_sessions", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_sessions.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_sessions"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_room_session", 200, json::object());
  (void)(client.video().room_sessions.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_room_session"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_room_session", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_sessions.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_room_session"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_listevents_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_session_events", 200, json::object());
  (void)(client.video().room_sessions.list_events("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_session_events"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_listevents_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_session_events", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_sessions.list_events("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_session_events"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_listmembers_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_session_members", 200, json::object());
  (void)(client.video().room_sessions.list_members("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_session_members"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_listmembers_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_session_members", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_sessions.list_members("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_session_members"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_listrecordings_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_session_recordings", 200, json::object());
  (void)(client.video().room_sessions.list_recordings("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_session_recordings"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_sessions_listrecordings_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_session_recordings", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_sessions.list_recordings("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_session_recordings"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_list_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_rooms", 200, json::object());
  (void)(client.video().rooms.list(std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_rooms"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_list_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_rooms", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.list(std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_rooms"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_room_by_name", 200, json::object());
  (void)(client.video().rooms.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_room_by_name"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_room_by_name", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_room_by_name"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_liststreams_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_streams", 200, json::object());
  (void)(client.video().rooms.list_streams("X", std::map<std::string, std::string>{}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_streams"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_liststreams_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.list_room_streams", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.list_streams("X", std::map<std::string, std::string>{}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.list_room_streams"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_streams_get_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_stream", 200, json::object());
  (void)(client.video().streams.get("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("GET"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_streams_get_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.get_stream", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().streams.get("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.get_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conference_tokens_reset_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.reset_conference_token", 200, json::object());
  (void)(client.video().conference_tokens.reset("X"));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.reset_conference_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conference_tokens_reset_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.reset_conference_token", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conference_tokens.reset("X"));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.reset_conference_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_video_conference", 200, json::object());
  (void)(client.video().conferences.create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_video_conference", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_createstream_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_conference_stream", 200, json::object());
  (void)(client.video().conferences.create_stream("X", {.url = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_conference_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_createstream_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_conference_stream", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.create_stream("X", {.url = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_conference_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_room_tokens_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_room_token", 200, json::object());
  (void)(client.video().room_tokens.create({.room_name = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_room_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_room_tokens_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_room_token", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().room_tokens.create({.room_name = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_room_token"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_create_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_room", 200, json::object());
  (void)(client.video().rooms.create(json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_room"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_create_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_room", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.create(json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_room"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_createstream_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_room_stream", 200, json::object());
  (void)(client.video().rooms.create_stream("X", {.url = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("POST"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_room_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_createstream_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.create_room_stream", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.create_stream("X", {.url = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.create_room_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.update_video_conference", 200, json::object());
  (void)(client.video().conferences.update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.update_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_conferences_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.update_video_conference", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().conferences.update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.update_video_conference"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.update_room", 200, json::object());
  (void)(client.video().rooms.update("X", json::object()));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.update_room"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_rooms_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.update_room", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().rooms.update("X", json::object()));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.update_room"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}

TEST(rest_mock_gen_video_streams_update_ok) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.update_stream", 200, json::object());
  (void)(client.video().streams.update("X", {.url = "X"}));
  {
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("PUT"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.update_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }
  return true;
}

TEST(rest_mock_gen_video_streams_update_err) {
  auto client = mocktest::make_client();
  mocktest::scenario_set("video.update_stream", 500, json{{"error", "x"}});
  bool threw = false;
  int status = 0;
  try {
    (void)(client.video().streams.update("X", {.url = "X"}));
  } catch (const SignalWireRestError& e) {
    threw = true;
    status = e.status();
  }
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("video.update_stream"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }
  return true;
}
