// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptAssistantEntry'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptAssistantEntry — generated read-side data type.
/// post-prompt components/schemas 'PostPromptAssistantEntry'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptAssistantEntry {
  std::optional<std::string> role;
  std::optional<std::string> content;
  std::optional<int> timestamp;
  std::optional<json> tool_calls;
  std::optional<double> latency;
  std::optional<double> utterance_latency;
  std::optional<double> audio_latency;
  std::optional<double> acoustic_latency;
  std::optional<double> eos_to_push_latency;
  std::optional<double> dg_decision_latency;
  std::optional<double> poll;
  std::optional<int> speech_start_wall_us;
  std::optional<int> last_word_end_wall_us;
  std::optional<int> turn_decided_wall_us;
  std::optional<int> status_pushed_wall_us;
  std::optional<json> stamps_us;
  std::optional<bool> barged;
  std::optional<double> barge_elapsed_ms;
  std::optional<std::string> text_heard_approx;
  std::optional<std::string> text_spoken_total;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
