// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptSwaigLogEntry'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptSwaigLogEntry — generated read-side data type.
/// post-prompt components/schemas 'PostPromptSwaigLogEntry'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptSwaigLogEntry {
  std::optional<std::string> command_name;
  std::optional<std::string> command_arg;
  std::optional<int> epoch_time;
  std::optional<bool> native;
  std::optional<json> active_count;
  std::optional<std::string> url;
  std::optional<json> post_data;
  std::optional<json> post_response;
  std::optional<json> delayed_post_response;
  std::optional<std::string> mcp_url;
  std::optional<std::string> mcp_tool;
  std::optional<json> mcp_response;
  std::optional<std::string> mcp_error;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
