// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptTiming'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptTiming — generated read-side data type.
/// post-prompt components/schemas 'PostPromptTiming'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptTiming {
  std::optional<double> hold_ms;
  std::optional<double> commit_latency_ms;
  std::optional<int> segments;
  std::optional<int> walkbacks;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
