// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptSystemLogEntry'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptSystemLogEntry — generated read-side data type.
/// post-prompt components/schemas 'PostPromptSystemLogEntry'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptSystemLogEntry {
  std::optional<std::string> role;
  std::optional<std::string> content;
  std::optional<int> timestamp;
  std::optional<std::string> action;
  std::optional<std::string> lang;
  std::optional<int> tokens;
  std::optional<std::string> content_type;
  std::optional<json> metadata;
  std::optional<std::string> context;
  std::optional<std::string> step;
  std::optional<int> step_index;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
