// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptUserEntry'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptUserEntry — generated read-side data type.
/// post-prompt components/schemas 'PostPromptUserEntry'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptUserEntry {
  std::optional<std::string> role;
  std::optional<std::string> content;
  std::optional<int> timestamp;
  std::optional<double> confidence;
  std::optional<std::string> content_type;
  std::optional<std::string> speaker;
  std::optional<int> start_timestamp;
  std::optional<int> end_timestamp;
  std::optional<double> speaking_to_final_event;
  std::optional<double> speaking_to_turn_detection;
  std::optional<double> turn_detection_to_final_event;
  std::optional<int> barge_count;
  std::optional<bool> merged;
  std::optional<int> merge_count;
  std::optional<json> entity;
  std::optional<json> eot;
  std::optional<json> timing;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
