// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptTimesEntry'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptTimesEntry — generated read-side data type.
/// post-prompt components/schemas 'PostPromptTimesEntry'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptTimesEntry {
  std::optional<std::string> response;
  std::optional<int> response_word_count;
  std::optional<double> answer_time;
  std::optional<double> token_time;
  std::optional<int> tokens;
  std::optional<double> avg_tps;
  std::optional<double> tps;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
