// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPrompt'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPrompt — generated read-side data type.
/// post-prompt components/schemas 'PostPrompt'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPrompt {
  std::optional<json> content_type;
  std::optional<json> content_disposition;
  std::optional<json> conversation_type;
  std::optional<json> action;
  std::optional<std::string> project_id;
  std::optional<std::string> space_id;
  std::optional<std::string> call_id;
  std::optional<std::string> app_name;
  std::optional<std::string> ai_session_id;
  std::optional<std::string> ai_id_tag;
  std::optional<std::string> conversation_id;
  std::optional<std::string> call_ended_by;
  std::optional<std::string> caller_id_name;
  std::optional<std::string> caller_id_number;
  std::optional<std::string> conversation_summary;
  std::optional<bool> hard_timeout;
  std::optional<int> call_start_date;
  std::optional<int> call_answer_date;
  std::optional<int> call_end_date;
  std::optional<int> ai_start_date;
  std::optional<int> ai_end_date;
  std::optional<json> post_prompt_data;
  std::optional<json> global_data;
  std::optional<json> SWMLVars;
  std::optional<json> SWMLCall;
  std::optional<json> call_log;
  std::optional<json> raw_call_log;
  std::optional<json> call_timeline;
  std::optional<json> previous_contexts;
  std::optional<json> times;
  std::optional<json> swaig_log;
  std::optional<double> total_minutes;
  std::optional<double> total_input_tokens;
  std::optional<double> total_output_tokens;
  std::optional<double> total_wire_input_tokens;
  std::optional<double> total_wire_input_tokens_per_minute;
  std::optional<double> total_wire_output_tokens;
  std::optional<double> total_wire_output_tokens_per_minute;
  std::optional<double> total_tts_chars;
  std::optional<double> total_tts_chars_per_min;
  std::optional<double> total_asr_minutes;
  std::optional<double> total_asr_cost_factor;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
