// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptStampsUs'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptStampsUs — generated read-side data type.
/// post-prompt components/schemas 'PostPromptStampsUs'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptStampsUs {
  std::optional<int> speech_start;
  std::optional<int> last_word_end;
  std::optional<int> suspected_end;
  std::optional<int> turn_decided;
  std::optional<int> status_pushed;
  std::optional<int> request_detect;
  std::optional<int> first_token;
  std::optional<int> first_utterance;
  std::optional<int> first_audio;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
