// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptData'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptData — generated read-side data type.
/// post-prompt components/schemas 'PostPromptData'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptData {
  std::optional<json> parsed;
  std::optional<std::string> raw;
  std::optional<std::string> substituted;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
