// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// post-prompt components/schemas 'PostPromptToolEntry'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace post_prompt_generated {

using json = nlohmann::json;

/// PostPromptToolEntry — generated read-side data type.
/// post-prompt components/schemas 'PostPromptToolEntry'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PostPromptToolEntry {
  std::optional<std::string> role;
  std::optional<std::string> tool_call_id;
  std::optional<std::string> content;
  std::optional<int> timestamp;
  std::optional<std::string> function_name;
  std::optional<double> latency;
  std::optional<double> utterance_latency;
  std::optional<double> function_latency;
  std::optional<double> audio_latency;
  std::optional<double> execution_latency;
  std::optional<std::string> deprecation_warning;
  std::optional<int> start_timestamp;
  std::optional<int> end_timestamp;
  std::optional<bool> distilled;
  std::optional<std::string> original_result;
  json extras = json::object();
};

}  // namespace post_prompt_generated
}  // namespace core
}  // namespace signalwire
