// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.amazon_bedrock', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingAmazonBedrockParams — generated read-side data type.
/// RELAY method 'calling.amazon_bedrock', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingAmazonBedrockParams {
  std::optional<json> SWAIG;
  std::optional<bool> async;
  std::optional<std::string> call_id;
  std::optional<json> global_data;
  std::optional<std::string> node_id;
  std::optional<json> params;
  std::optional<json> post_prompt;
  std::optional<std::string> post_prompt_url;
  std::optional<json> prompt;
  std::optional<bool> swml;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
