// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.receive', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingReceiveParams — generated read-side data type.
/// RELAY method 'calling.receive', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingReceiveParams {
  std::optional<std::string> context;
  std::optional<json> contexts;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
