// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.collect', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingCollectParams — generated read-side data type.
/// RELAY method 'calling.collect', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingCollectParams {
  std::optional<std::string> call_id;
  std::optional<bool> continue_;  // wire key: continue
  std::optional<bool> continuous;
  std::optional<std::string> control_id;
  std::optional<json> digits;
  std::optional<double> initial_timeout;
  std::optional<std::string> node_id;
  std::optional<bool> partial_results;
  std::optional<bool> send_start_of_input;
  std::optional<json> speech;
  std::optional<bool> start_input_timers;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
