// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.bind_digit', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingBindDigitParams — generated read-side data type.
/// RELAY method 'calling.bind_digit', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingBindDigitParams {
  std::optional<std::string> bind_method;
  std::optional<std::string> call_id;
  std::optional<std::string> digits;
  std::optional<int> max_triggers;
  std::optional<std::string> node_id;
  std::optional<json> params;
  std::optional<std::string> realm;
  std::optional<bool> swml;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
