// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.join_conference', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingJoinConferenceParams — generated read-side data type.
/// RELAY method 'calling.join_conference', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingJoinConferenceParams {
  std::optional<std::string> acl;
  std::optional<std::string> beep;
  std::optional<std::string> call_id;
  std::optional<std::string> coach;
  std::optional<bool> end_on_exit;
  std::optional<int> max_participants;
  std::optional<bool> muted;
  std::optional<std::string> name;
  std::optional<std::string> node_id;
  std::optional<std::string> record;
  std::optional<std::string> recording_status_callback;
  std::optional<std::string> recording_status_callback_event;
  std::optional<std::string> recording_status_callback_event_type;
  std::optional<std::string> recording_status_callback_method;
  std::optional<std::string> region;
  std::optional<bool> start_on_enter;
  std::optional<std::string> status_callback;
  std::optional<std::string> status_callback_event;
  std::optional<std::string> status_callback_event_type;
  std::optional<std::string> status_callback_method;
  std::optional<json> stream;
  std::optional<bool> swml;
  std::optional<std::string> trim;
  std::optional<std::string> wait_url;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
