// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.pay', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingPayParams — generated read-side data type.
/// RELAY method 'calling.pay', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingPayParams {
  std::optional<json> bank_account_type;
  std::optional<std::string> call_id;
  std::optional<std::string> charge_amount;
  std::optional<std::string> control_id;
  std::optional<std::string> currency;
  std::optional<std::string> description;
  std::optional<json> input;
  std::optional<std::string> language;
  std::optional<std::string> max_attempts;
  std::optional<std::string> min_postal_code_length;
  std::optional<std::string> node_id;
  std::optional<json> parameters;
  std::optional<std::string> payment_connector_url;
  std::optional<json> payment_method;
  std::optional<std::string> postal_code;
  std::optional<json> prompts;
  std::optional<std::string> security_code;
  std::optional<std::string> status_url;
  std::optional<std::string> timeout;
  std::optional<json> token_type;
  std::optional<std::string> valid_card_types;
  std::optional<std::string> voice;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
