// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'calling.connect', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// CallingConnectParams — generated read-side data type.
/// RELAY method 'calling.connect', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallingConnectParams {
  std::optional<std::string> call_id;
  std::optional<json> devices;
  std::optional<int> max_duration;
  std::optional<double> max_price_per_minute;
  std::optional<std::string> node_id;
  std::optional<json> ringback;
  std::optional<std::string> tag;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
