// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'messaging.send', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// MessagingSendParams — generated read-side data type.
/// RELAY method 'messaging.send', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct MessagingSendParams {
  std::optional<std::string> body;
  std::optional<std::string> context;
  std::optional<std::string> from_number;
  std::optional<json> media;
  std::optional<std::string> region;
  std::optional<json> tags;
  std::optional<std::string> to_number;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
