// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'signalwire.execute', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// SignalwireExecuteParams — generated read-side data type.
/// RELAY method 'signalwire.execute', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SignalwireExecuteParams {
  std::optional<json> attempted;
  std::optional<std::string> method;
  std::optional<json> params;
  std::optional<std::string> protocol;
  std::optional<std::string> requester_identity;
  std::optional<std::string> requester_nodeid;
  std::optional<std::string> responder_identity;
  std::optional<std::string> responder_nodeid;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
