// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_relay_protocol.py; DO NOT EDIT.
//
// RELAY method 'signalwire.connect', params.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace relay {
namespace protocol_types_generated {

using json = nlohmann::json;

/// SignalwireConnectParams — generated read-side data type.
/// RELAY method 'signalwire.connect', params.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SignalwireConnectParams {
  std::optional<std::string> agent;
  std::optional<json> authentication;
  std::optional<std::string> host;
  std::optional<std::string> identity;
  std::optional<json> params;
  std::optional<json> protocols;
  std::optional<json> version;
  json extras = json::object();
};

}  // namespace protocol_types_generated
}  // namespace relay
}  // namespace signalwire
