// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// swaig-response action 'context_switch' value object.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swaig_actions_generated {

using json = nlohmann::json;

/// ContextSwitchAction — generated read-side data type.
/// swaig-response action 'context_switch' value object.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct ContextSwitchAction {
  std::optional<json> system_prompt;
  std::optional<json> user_prompt;
  std::optional<json> system_pom;
  std::optional<json> user_pom;
  std::optional<bool> consolidate;
  std::optional<bool> full_reset;
  json extras = json::object();
};

}  // namespace swaig_actions_generated
}  // namespace core
}  // namespace signalwire
