// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// swaig-response action 'hold' value object.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swaig_actions_generated {

using json = nlohmann::json;

/// HoldAction — generated read-side data type.
/// swaig-response action 'hold' value object.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct HoldAction {
  std::optional<int> timeout;
  json extras = json::object();
};

}  // namespace swaig_actions_generated
}  // namespace core
}  // namespace signalwire
