// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// swaig-response components/schemas 'SwaigAction'. A response-action object. The keys below are the
// full vocabulary dispatched by actions.c::process_action; an action object sets one or more of
// them. Each key's source line is the engine dispatch site.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swaig_actions_generated {

using json = nlohmann::json;

/// SwaigAction — generated read-side data type.
/// swaig-response components/schemas 'SwaigAction'. A response-action object. The keys below are
/// the full vocabulary dispatched by actions.c::process_action; an action object sets one or more
/// of them. Each key's source line is the engine dispatch site.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SwaigAction {
  std::optional<json> SWML;
  std::optional<json> add_dynamic_hints;
  std::optional<json> back_to_back_functions;
  std::optional<std::string> change_context;
  std::optional<std::string> change_step;
  std::optional<bool> clear_dynamic_hints;
  std::optional<json> context_switch;
  std::optional<int> end_of_speech_timeout;
  std::optional<bool> extensive_data;
  std::optional<bool> functions_on_speaker_timeout;
  std::optional<bool> hangup;
  std::optional<json> hold;
  std::optional<json> playback_bg;
  std::optional<json> replace_in_history;
  std::optional<std::string> say;
  std::optional<json> set_global_data;
  std::optional<json> set_meta_data;
  std::optional<json> settings;
  std::optional<int> speech_event_timeout;
  std::optional<bool> stop;
  std::optional<bool> stop_playback_bg;
  std::optional<json> toggle_functions;
  std::optional<json> transfer;
  std::optional<json> unset_global_data;
  std::optional<json> unset_meta_data;
  std::optional<json> user_event;
  std::optional<std::string> user_input;
  std::optional<json> wait_for_user;
  json extras = json::object();
};

}  // namespace swaig_actions_generated
}  // namespace core
}  // namespace signalwire
