// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// swaig-response components/schemas 'SwaigResponse'. Parsed at actions.c:2228-2276.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swaig_actions_generated {

using json = nlohmann::json;

/// SwaigResponse — generated read-side data type.
/// swaig-response components/schemas 'SwaigResponse'. Parsed at actions.c:2228-2276.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SwaigResponse {
  std::optional<std::string> response;
  std::optional<json> action;
  std::optional<bool> post_process;
  json extras = json::object();
};

}  // namespace swaig_actions_generated
}  // namespace core
}  // namespace signalwire
