// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiConfig — generated read-side data type.
/// schema.json $defs schema 'AiConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiConfig {
  std::optional<json> SWAIG;
  std::optional<json> agent;
  std::optional<json> engine;
  std::optional<json> global_data;
  std::optional<json> hints;
  std::optional<json> languages;
  std::optional<json> multilingual;
  std::optional<json> params;
  std::optional<json> post_prompt;
  std::optional<json> post_prompt_auth_password;
  std::optional<json> post_prompt_auth_user;
  std::optional<json> post_prompt_url;
  std::optional<json> prompt;
  std::optional<json> pronounce;
  std::optional<json> voice;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
