// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiLanguagesItemParams'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiLanguagesItemParams — generated read-side data type.
/// schema.json $defs schema 'AiLanguagesItemParams'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiLanguagesItemParams {
  std::optional<std::string> emotion;
  std::optional<json> pitch;
  std::optional<json> similarity;
  std::optional<json> speakingRate;
  std::optional<json> speed;
  std::optional<json> stability;
  std::optional<json> streaming;
  std::optional<json> temperature;
  std::optional<json> vol;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
