// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiMultilingual'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiMultilingual — generated read-side data type.
/// schema.json $defs schema 'AiMultilingual'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiMultilingual {
  std::optional<json> allowed;
  std::optional<std::string> engine;
  std::optional<json> fillers;
  std::optional<json> function_fillers;
  std::optional<json> languages;
  std::optional<double> min_switch_words;
  std::optional<std::string> model;
  std::optional<std::string> provider;
  std::optional<std::string> start_language;
  std::optional<json> turn_fillers;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
