// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiParamsRealtime'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiParamsRealtime — generated read-side data type.
/// schema.json $defs schema 'AiParamsRealtime'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiParamsRealtime {
  std::optional<std::string> input_transcription;
  std::optional<json> local_vad;
  std::optional<json> local_vad_frame_ms;
  std::optional<json> local_vad_threshold;
  std::optional<std::string> noise_reduction;
  std::optional<json> packets_per_send;
  std::optional<std::string> reasoning_effort;
  std::optional<json> speed;
  std::optional<json> temperature;
  std::optional<std::string> tool_model;
  std::optional<std::string> vad_eagerness;
  std::optional<json> vad_prefix_padding_ms;
  std::optional<json> vad_silence_duration_ms;
  std::optional<json> vad_threshold;
  std::optional<std::string> vad_type;
  std::optional<std::string> voice;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
