// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiParamsConvoItem'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiParamsConvoItem — generated read-side data type.
/// schema.json $defs schema 'AiParamsConvoItem'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiParamsConvoItem {
  std::optional<std::string> content;
  std::optional<std::string> lang;
  std::optional<std::string> role;
  std::optional<std::string> tool_call_id;
  std::optional<json> tool_calls;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
