// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiParams'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiParams — generated read-side data type.
/// schema.json $defs schema 'AiParams'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiParams {
  std::optional<json> acknowledge_interruptions;
  std::optional<json> acoustic_eot_gate_prob;
  std::optional<json> acoustic_eot_trust_prob;
  std::optional<std::string> ai_model;
  std::optional<std::string> ai_name;
  std::optional<json> ai_volume;
  std::optional<std::string> app_name;
  std::optional<json> asr_diarize;
  std::optional<json> asr_params;
  std::optional<json> asr_smart_format;
  std::optional<json> asr_speaker_affinity;
  std::optional<std::string> attention_escalate_prompt;
  std::optional<json> attention_timeout;
  std::optional<std::string> attention_timeout_prompt;
  std::optional<std::string> auth_token;
  std::optional<json> auto_correct;
  std::optional<json> azure_stream_first;
  std::optional<std::string> azure_tts_key;
  std::optional<std::string> background_file;
  std::optional<json> background_file_loops;
  std::optional<json> background_file_volume;
  std::optional<json> barge_functions;
  std::optional<std::string> barge_match_string;
  std::optional<json> barge_min_words;
  std::optional<json> bill_all_tts;
  std::optional<json> cache;
  std::optional<std::string> call_uuid;
  std::optional<std::string> cartesia_key;
  std::optional<std::string> cartesia_model;
  std::optional<json> cartesia_stream_first;
  std::optional<json> confidence;
  std::optional<std::string> conscience;
  std::optional<std::string> conversation_id;
  std::optional<json> conversation_sliding_window;
  std::optional<json> convo;
  std::optional<json> debug_webhook_level;
  std::optional<std::string> debug_webhook_url;
  std::optional<std::string> deepgram_key_override;
  std::optional<json> deepgram_stream_first;
  std::optional<std::string> deepgram_tts_key;
  std::optional<std::string> deepgram_url_override;
  std::optional<std::string> developer_prompt;
  std::optional<std::string> digit_terminators;
  std::optional<json> digit_timeout;
  std::optional<std::string> direction;
  std::optional<json> double_turn_filler_every_n;
  std::optional<json> double_turn_filler_min_ms;
  std::optional<std::string> double_turn_model;
  std::optional<std::string> double_turn_prompt;
  std::optional<json> double_turn_wait_ms;
  std::optional<json> double_turns;
  std::optional<std::string> eleven_labs_key;
  std::optional<std::string> eleven_labs_model;
  std::optional<json> eleven_labs_similarity;
  std::optional<json> eleven_labs_stability;
  std::optional<json> eleven_labs_stream_first;
  std::optional<json> enable_barge;
  std::optional<json> enable_inner_dialog;
  std::optional<json> enable_pause;
  std::optional<std::string> enable_text_normalization;
  std::optional<json> enable_thinking;
  std::optional<json> enable_turn_detection;
  std::optional<json> enable_vision;
  std::optional<json> end_of_speech_timeout;
  std::optional<json> energy_level;
  std::optional<json> escalate_after_ms;
  std::optional<json> escalate_after_turns;
  std::optional<std::string> event_webhook_url;
  std::optional<std::string> ext;
  std::optional<json> first_word_timeout;
  std::optional<std::string> fish_key;
  std::optional<std::string> fish_model;
  std::optional<json> function_filler_sequence_gap_ms;
  std::optional<json> function_wait_for_talking;
  std::optional<json> functions_on_no_response;
  std::optional<std::string> grok_key;
  std::optional<std::string> groq_tts_key;
  std::optional<std::string> hard_stop_prompt;
  std::optional<std::string> hard_stop_time;
  std::optional<std::string> hold_music;
  std::optional<json> hold_on_process;
  std::optional<json> inactivity_timeout;
  std::optional<json> initial_sleep_ms;
  std::optional<json> inner_dialog;
  std::optional<std::string> inner_dialog_model;
  std::optional<std::string> inner_dialog_prompt;
  std::optional<json> inner_dialog_scorecard;
  std::optional<json> input_poll_freq;
  std::optional<json> interrupt_on_noise;
  std::optional<std::string> interrupt_prompt;
  std::optional<std::string> inworld_apikey;
  std::optional<std::string> inworld_key;
  std::optional<std::string> inworld_model;
  std::optional<std::string> language;
  std::optional<json> languages_enabled;
  std::optional<json> lipsync_debug;
  std::optional<json> llm_diarize_aware;
  std::optional<std::string> local_tz;
  std::optional<json> max_emotion;
  std::optional<json> max_response_tokens;
  std::optional<json> min_utterance_ms;
  std::optional<std::string> minimax_key;
  std::optional<std::string> minimax_model;
  std::optional<std::string> mistral_key;
  std::optional<std::string> mistral_model;
  std::optional<std::string> model;
  std::optional<std::string> openai_asr_engine;
  std::optional<json> openai_azure;
  std::optional<std::string> openai_gcloud_version;
  std::optional<json> openai_stream_first;
  std::optional<std::string> openai_tts_key;
  std::optional<std::string> openai_tts_url;
  std::optional<json> outbound_attention_timeout;
  std::optional<json> pcm_channels;
  std::optional<json> pcm_rate;
  std::optional<json> persist_global_data;
  std::optional<std::string> pom_format;
  std::optional<std::string> provider;
  std::optional<std::string> pvt_params;
  std::optional<json> realtime;
  std::optional<std::string> redact_prompt;
  std::optional<std::string> rime_apikey;
  std::optional<std::string> rime_key;
  std::optional<std::string> rime_model;
  std::optional<json> rime_stream_first;
  std::optional<json> sample_rate;
  std::optional<json> save_conversation;
  std::optional<json> send_single_llm_response;
  std::optional<json> similarity;
  std::optional<std::string> smallest_key;
  std::optional<std::string> smallest_model;
  std::optional<json> speak_when_spoken_to;
  std::optional<std::string> speaker;
  std::optional<json> speech_event_timeout;
  std::optional<json> speech_gen_quick_stops;
  std::optional<json> speech_timeout;
  std::optional<std::string> speechify_key;
  std::optional<json> speechify_loudness_normalization;
  std::optional<std::string> speechify_model;
  std::optional<std::string> speechify_output_format;
  std::optional<json> speechify_stream_first;
  std::optional<json> speechify_text_normalization;
  std::optional<json> speed;
  std::optional<json> stability;
  std::optional<json> start_paused;
  std::optional<std::string> static_greeting;
  std::optional<json> static_greeting_no_barge;
  std::optional<json> stream_first;
  std::optional<json> streaming;
  std::optional<std::string> strict_mode;
  std::optional<std::string> summary_mode;
  std::optional<json> swaig_allow_settings;
  std::optional<json> swaig_allow_swml;
  std::optional<json> swaig_post_conversation;
  std::optional<json> swaig_post_swml_vars;
  std::optional<json> swaig_set_global_data;
  std::optional<json> target_first_segment_ms;
  std::optional<std::string> text_normalization_far_dir;
  std::optional<std::string> thinking_model;
  std::optional<json> tool_result_distill;
  std::optional<json> transfer_summary;
  std::optional<json> transparent_barge;
  std::optional<json> transparent_barge_max_time;
  std::optional<std::string> tts_number_format;
  std::optional<json> turn_detection;
  std::optional<json> turn_detection_min_length;
  std::optional<json> turn_detection_timeout;
  std::optional<json> turn_filler_every_n;
  std::optional<json> turn_filler_min_ms;
  std::optional<std::string> turn_filler_sources;
  std::optional<std::string> url;
  std::optional<std::string> utility_model;
  std::optional<std::string> vad_config;
  std::optional<json> video_fps;
  std::optional<std::string> video_idle_file;
  std::optional<std::string> video_listening_file;
  std::optional<std::string> video_scale;
  std::optional<std::string> video_talking_file;
  std::optional<std::string> vision_model;
  std::optional<std::string> voice_name;
  std::optional<json> vol;
  std::optional<json> wait_for_user;
  std::optional<std::string> wake_prefix;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
