// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiPostPrompt'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiPostPrompt — generated read-side data type.
/// schema.json $defs schema 'AiPostPrompt'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiPostPrompt {
  std::optional<json> frequency_penalty;
  std::optional<double> max_completion_tokens;
  std::optional<double> max_tokens;
  std::optional<std::string> model;
  std::optional<json> pom;
  std::optional<json> presence_penalty;
  std::optional<std::string> reasoning_effort;
  std::optional<double> temperature;
  std::optional<std::string> text;
  std::optional<double> top_p;
  std::optional<std::string> verbosity;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
