// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiSWAIG'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiSWAIG — generated read-side data type.
/// schema.json $defs schema 'AiSWAIG'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiSWAIG {
  std::optional<json> defaults;
  std::optional<json> functions;
  std::optional<json> hooks;
  std::optional<json> includes;
  std::optional<json> internal_fillers;
  std::optional<json> mcp_servers;
  std::optional<json> native_functions;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
