// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiSidecarConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiSidecarConfig — generated read-side data type.
/// schema.json $defs schema 'AiSidecarConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiSidecarConfig {
  std::optional<json> SWAIG;
  std::optional<json> action;
  std::optional<json> customer_role;
  std::optional<json> direction;
  std::optional<json> global_data;
  std::optional<json> hints;
  std::optional<json> lang;
  std::optional<json> model;
  std::optional<json> params;
  std::optional<json> permissions;
  std::optional<json> prompt;
  std::optional<json> url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
