// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiSidecarParams'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiSidecarParams — generated read-side data type.
/// schema.json $defs schema 'AiSidecarParams'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiSidecarParams {
  std::optional<json> act_on_channel;
  std::optional<json> ai_summary;
  std::optional<json> ai_summary_prompt;
  std::optional<json> debug;
  std::optional<json> debug_level;
  std::optional<json> deepgram_key_override;
  std::optional<json> deepgram_url_override;
  std::optional<json> final_summary;
  std::optional<json> idle_timeout_ms;
  std::optional<json> live_events;
  std::optional<json> max_history_tokens;
  std::optional<json> max_iters_per_tick;
  std::optional<json> min_interval_ms;
  std::optional<json> speech_engine;
  std::optional<json> speech_timeout;
  std::optional<json> summary_model;
  std::optional<json> transcribe_prompt;
  std::optional<json> vad_silence_ms;
  std::optional<json> vad_thresh;
  std::optional<json> verbose_utterances;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
