// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiSidecarSWAIGFunctionsItem'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiSidecarSWAIGFunctionsItem — generated read-side data type.
/// schema.json $defs schema 'AiSidecarSWAIGFunctionsItem'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiSidecarSWAIGFunctionsItem {
  std::optional<json> description;
  std::optional<json> function;
  std::optional<json> parameters;
  std::optional<json> purpose;
  std::optional<json> web_hook_auth_pass;
  std::optional<json> web_hook_auth_password;
  std::optional<json> web_hook_auth_user;
  std::optional<json> web_hook_url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
