// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AiSWAIGInternalFillers'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AiSWAIGInternalFillers — generated read-side data type.
/// schema.json $defs schema 'AiSWAIGInternalFillers'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AiSWAIGInternalFillers {
  std::optional<json> adjust_response_latency;
  std::optional<json> change_context;
  std::optional<json> check_time;
  std::optional<json> get_ideal_strategy;
  std::optional<json> get_visual_input;
  std::optional<json> next_step;
  std::optional<json> pause_conversation;
  std::optional<json> wait_for_user;
  std::optional<json> wait_seconds;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
