// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AmazonBedrockConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AmazonBedrockConfig — generated read-side data type.
/// schema.json $defs schema 'AmazonBedrockConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AmazonBedrockConfig {
  std::optional<json> SWAIG;
  std::optional<std::string> app_name;
  std::optional<std::string> assistant_name;
  std::optional<std::string> assistant_prompt;
  std::optional<std::string> conversation_id;
  std::optional<json> global_data;
  std::optional<json> greeting_prompt;
  std::optional<json> params;
  std::optional<json> post_prompt;
  std::optional<std::string> post_prompt_url;
  std::optional<json> prompt;
  std::optional<std::string> transcript_webhook_url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
