// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AmazonBedrockParams'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AmazonBedrockParams — generated read-side data type.
/// schema.json $defs schema 'AmazonBedrockParams'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AmazonBedrockParams {
  std::optional<json> attention_timeout;
  std::optional<std::string> compact_conversation_time;
  std::optional<std::string> compact_strategy;
  std::optional<std::string> hard_stop_prompt;
  std::optional<std::string> hard_stop_time;
  std::optional<json> inactivity_timeout;
  std::optional<std::string> video_idle_file;
  std::optional<std::string> video_listening_file;
  std::optional<std::string> video_talking_file;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
