// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'AmazonBedrockPrompt'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// AmazonBedrockPrompt — generated read-side data type.
/// schema.json $defs schema 'AmazonBedrockPrompt'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct AmazonBedrockPrompt {
  std::optional<json> pom;
  std::optional<json> temperature;
  std::optional<std::string> text;
  std::optional<json> top_p;
  std::optional<std::string> voice_id;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
