// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'CallPayPrompts'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// CallPayPrompts — generated read-side data type.
/// schema.json $defs schema 'CallPayPrompts'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallPayPrompts {
  std::optional<json> actions;
  std::optional<json> attempt;
  std::optional<json> card_type;
  std::optional<json> error_type;
  std::optional<json> for_;  // wire key: for
  std::optional<json> play;
  std::optional<json> require_matching_inputs;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
