// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'CallDeviceStream'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// CallDeviceStream — generated read-side data type.
/// schema.json $defs schema 'CallDeviceStream'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct CallDeviceStream {
  std::optional<json> authorization_bearer_token;
  std::optional<json> codec;
  std::optional<json> custom_parameters;
  std::optional<json> name;
  std::optional<json> realtime;
  std::optional<json> status_url;
  std::optional<json> status_url_method;
  std::optional<json> url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
