// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'ConnectSwitch'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// ConnectSwitch — generated read-side data type.
/// schema.json $defs schema 'ConnectSwitch'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct ConnectSwitch {
  std::optional<std::string> variable;
  std::optional<json> case_;     // wire key: case
  std::optional<json> default_;  // wire key: default
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
