// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'ConnectConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// ConnectConfig — generated read-side data type.
/// schema.json $defs schema 'ConnectConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct ConnectConfig {
  std::optional<json> answer_on_bridge;
  std::optional<json> authorization_bearer_token;
  std::optional<json> call_state_events;
  std::optional<json> call_state_url;
  std::optional<json> codec;
  std::optional<json> codecs;
  std::optional<json> confirm;
  std::optional<json> confirm_timeout;
  std::optional<json> custom_parameters;
  std::optional<json> encryption;
  std::optional<json> execute_after_queue;
  std::optional<json> from;
  std::optional<json> from_name;
  std::optional<json> headers;
  std::optional<json> max_duration;
  std::optional<json> name;
  std::optional<json> parallel;
  std::optional<json> password;
  std::optional<json> realtime;
  std::optional<json> result;
  std::optional<json> ringback;
  std::optional<json> serial;
  std::optional<json> serial_parallel;
  std::optional<json> session_timeout;
  std::optional<json> status_url;
  std::optional<json> status_url_method;
  std::optional<json> stop_all_on_reject;
  std::optional<json> timeout;
  std::optional<json> to;
  std::optional<json> username;
  std::optional<json> webrtc_media;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
