// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'ConnectDeviceParallel'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// ConnectDeviceParallel — generated read-side data type.
/// schema.json $defs schema 'ConnectDeviceParallel'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct ConnectDeviceParallel {
  std::optional<std::string> from;
  std::optional<json> headers;
  std::optional<std::string> codecs;
  std::optional<json> webrtc_media;
  std::optional<json> session_timeout;
  std::optional<json> ringback;
  std::optional<json> result;
  std::optional<json> timeout;
  std::optional<json> max_duration;
  std::optional<json> answer_on_bridge;
  std::optional<json> confirm;
  std::optional<json> confirm_timeout;
  std::optional<std::string> username;
  std::optional<std::string> password;
  std::optional<json> encryption;
  std::optional<std::string> call_state_url;
  std::optional<json> transfer_after_bridge;
  std::optional<json> call_state_events;
  std::optional<json> parallel;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
