// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'Context'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// Context — generated read-side data type.
/// schema.json $defs schema 'Context'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct Context {
  std::optional<json> consolidate;
  std::optional<json> enter_fillers;
  std::optional<json> exit_fillers;
  std::optional<json> full_reset;
  std::optional<std::string> history;
  std::optional<std::string> initial_step;
  std::optional<json> isolated;
  std::optional<json> pom;
  std::optional<json> post_prompt;
  std::optional<std::string> prompt;
  std::optional<json> reset;
  std::optional<json> steps;
  std::optional<std::string> system_prompt;
  std::optional<std::string> user_prompt;
  std::optional<json> valid_contexts;
  std::optional<json> valid_steps;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
