// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'ContextsTextObject'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// ContextsTextObject — generated read-side data type.
/// schema.json $defs schema 'ContextsTextObject'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct ContextsTextObject {
  std::optional<json> steps;
  std::optional<bool> isolated;
  std::optional<json> enter_fillers;
  std::optional<json> exit_fillers;
  std::optional<std::string> text;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
