// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// flattened SWMLMethod verb 'detect_machine' config.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// DetectMachineConfig — generated read-side data type.
/// flattened SWMLMethod verb 'detect_machine' config.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct DetectMachineConfig {
  std::optional<json> detect_message_end;
  std::optional<std::string> detectors;
  std::optional<json> end_silence_timeout;
  std::optional<json> initial_timeout;
  std::optional<json> machine_ready_timeout;
  std::optional<json> machine_voice_threshold;
  std::optional<json> machine_words_threshold;
  std::optional<std::string> status_url;
  std::optional<json> timeout;
  std::optional<json> tone;
  std::optional<json> wait;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
