// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'EnterQueueConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// EnterQueueConfig — generated read-side data type.
/// schema.json $defs schema 'EnterQueueConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct EnterQueueConfig {
  std::optional<json> execute_after_queue;
  std::optional<json> queue_name;
  std::optional<json> status_url;
  std::optional<json> wait_time;
  std::optional<json> wait_url;
  std::optional<json> whisper_url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
