// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'ExecuteConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// ExecuteConfig — generated read-side data type.
/// schema.json $defs schema 'ExecuteConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct ExecuteConfig {
  std::optional<json> dest;
  std::optional<json> meta;
  std::optional<json> on_return;
  std::optional<json> params;
  std::optional<json> result;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
