// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'JoinConferenceObject'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// JoinConferenceObject — generated read-side data type.
/// schema.json $defs schema 'JoinConferenceObject'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct JoinConferenceObject {
  std::optional<std::string> name;
  std::optional<json> muted;
  std::optional<json> beep;
  std::optional<json> start_on_enter;
  std::optional<json> end_on_exit;
  std::optional<json> wait_url;
  std::optional<json> max_participants;
  std::optional<json> record;
  std::optional<std::string> region;
  std::optional<json> trim;
  std::optional<std::string> coach;
  std::optional<json> status_callback_event;
  std::optional<std::string> status_callback;
  std::optional<json> status_callback_method;
  std::optional<std::string> recording_status_callback;
  std::optional<json> recording_status_callback_method;
  std::optional<json> recording_status_callback_event;
  std::optional<json> result;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
