// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'JoinConferenceConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// JoinConferenceConfig — generated read-side data type.
/// schema.json $defs schema 'JoinConferenceConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct JoinConferenceConfig {
  std::optional<json> beep;
  std::optional<json> coach;
  std::optional<json> emit_call_quality;
  std::optional<json> end_on_exit;
  std::optional<json> max_participants;
  std::optional<json> meta;
  std::optional<json> min_participants;
  std::optional<json> muted;
  std::optional<json> name;
  std::optional<json> record;
  std::optional<json> recording_status_callback;
  std::optional<json> recording_status_callback_event;
  std::optional<json> recording_status_callback_event_type;
  std::optional<json> recording_status_callback_method;
  std::optional<json> region;
  std::optional<json> start_on_enter;
  std::optional<json> status_callback;
  std::optional<json> status_callback_event;
  std::optional<json> status_callback_event_type;
  std::optional<json> status_callback_method;
  std::optional<json> stream;
  std::optional<json> trim;
  std::optional<json> video;
  std::optional<json> video_layout;
  std::optional<json> video_preview;
  std::optional<json> video_quality;
  std::optional<json> wait_url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
