// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'LanguagesWithSoloFillers'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// LanguagesWithSoloFillers — generated read-side data type.
/// schema.json $defs schema 'LanguagesWithSoloFillers'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct LanguagesWithSoloFillers {
  std::optional<std::string> name;
  std::optional<std::string> code;
  std::optional<std::string> voice;
  std::optional<std::string> model;
  std::optional<std::string> emotion;
  std::optional<std::string> speed;
  std::optional<std::string> engine;
  std::optional<json> params;
  std::optional<json> fillers;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
