// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'LiveTranslateActionStart'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// LiveTranslateActionStart — generated read-side data type.
/// schema.json $defs schema 'LiveTranslateActionStart'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct LiveTranslateActionStart {
  std::optional<json> ai_summary;
  std::optional<json> ai_summary_prompt;
  std::optional<json> debug_level;
  std::optional<json> deepgram_key_override;
  std::optional<json> deepgram_url_override;
  std::optional<json> direction;
  std::optional<json> filter_from;
  std::optional<json> filter_to;
  std::optional<json> from_lang;
  std::optional<json> from_voice;
  std::optional<json> from_voice_params;
  std::optional<json> live_events;
  std::optional<json> mode;
  std::optional<json> speech_engine;
  std::optional<json> speech_timeout;
  std::optional<json> to_lang;
  std::optional<json> to_voice;
  std::optional<json> to_voice_params;
  std::optional<json> translation_model;
  std::optional<json> translation_model_params;
  std::optional<json> vad_silence_ms;
  std::optional<json> vad_thresh;
  std::optional<json> webhook;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
