// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'NumberProperty'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// NumberProperty — generated read-side data type.
/// schema.json $defs schema 'NumberProperty'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct NumberProperty {
  std::optional<std::string> description;
  std::optional<json> nullable;
  std::optional<std::string> type;
  std::optional<json> enum_;     // wire key: enum
  std::optional<json> default_;  // wire key: default
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
