// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'OmitPropertiesBedrockPostPomptTextOmittedPromptProps'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// OmitPropertiesBedrockPostPomptTextOmittedPromptProps — generated read-side data type.
/// schema.json $defs schema 'OmitPropertiesBedrockPostPomptTextOmittedPromptProps'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct OmitPropertiesBedrockPostPomptTextOmittedPromptProps {
  std::optional<int> max_tokens;
  std::optional<json> temperature;
  std::optional<json> top_p;
  std::optional<json> confidence;
  std::optional<json> presence_penalty;
  std::optional<json> frequency_penalty;
  std::optional<std::string> text;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
