// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'OmitPropertiesBedrockPromptPomOmittedPromptProps'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// OmitPropertiesBedrockPromptPomOmittedPromptProps — generated read-side data type.
/// schema.json $defs schema 'OmitPropertiesBedrockPromptPomOmittedPromptProps'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct OmitPropertiesBedrockPromptPomOmittedPromptProps {
  std::optional<json> voice_id;
  std::optional<int> max_tokens;
  std::optional<json> temperature;
  std::optional<json> top_p;
  std::optional<json> confidence;
  std::optional<json> presence_penalty;
  std::optional<json> frequency_penalty;
  std::optional<json> pom;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
