// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'PayPrompts'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PayPrompts — generated read-side data type.
/// schema.json $defs schema 'PayPrompts'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PayPrompts {
  std::optional<json> actions;
  std::optional<std::string> for_;  // wire key: for
  std::optional<std::string> attempts;
  std::optional<std::string> card_type;
  std::optional<std::string> error_type;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
