// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'PayConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PayConfig — generated read-side data type.
/// schema.json $defs schema 'PayConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PayConfig {
  std::optional<json> description;
  std::optional<json> bank_account_type;
  std::optional<json> charge_amount;
  std::optional<json> currency;
  std::optional<json> input;
  std::optional<json> language;
  std::optional<json> max_attempts;
  std::optional<json> min_postal_code_length;
  std::optional<json> parameters;
  std::optional<json> payment_connector_url;
  std::optional<json> payment_method;
  std::optional<json> postal_code;
  std::optional<json> prompts;
  std::optional<json> say_voice;
  std::optional<json> security_code;
  std::optional<json> status_url;
  std::optional<json> timeout;
  std::optional<json> token_type;
  std::optional<json> valid_card_types;
  std::optional<json> voice;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
