// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// flattened SWMLMethod verb 'pay' config.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PayConfig — generated read-side data type.
/// flattened SWMLMethod verb 'pay' config.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PayConfig {
  std::optional<std::string> payment_connector_url;
  std::optional<std::string> charge_amount;
  std::optional<std::string> currency;
  std::optional<std::string> description;
  std::optional<std::string> input;
  std::optional<std::string> language;
  std::optional<json> max_attempts;
  std::optional<json> min_postal_code_length;
  std::optional<json> parameters;
  std::optional<std::string> payment_method;
  std::optional<json> postal_code;
  std::optional<json> prompts;
  std::optional<json> security_code;
  std::optional<std::string> status_url;
  std::optional<json> timeout;
  std::optional<json> token_type;
  std::optional<std::string> valid_card_types;
  std::optional<std::string> voice;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
