// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema
// 'PickPropertiesSummarizeConversationSWAIGFunctionPickedSWAIGFunctionProps'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PickPropertiesSummarizeConversationSWAIGFunctionPickedSWAIGFunctionProps — generated read-side
/// data type. schema.json $defs schema
/// 'PickPropertiesSummarizeConversationSWAIGFunctionPickedSWAIGFunctionProps'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PickPropertiesSummarizeConversationSWAIGFunctionPickedSWAIGFunctionProps {
  std::optional<std::string> description;
  std::optional<json> parameters;
  std::optional<json> active;
  std::optional<json> meta_data;
  std::optional<std::string> meta_data_token;
  std::optional<json> data_map;
  std::optional<std::string> web_hook_url;
  std::optional<std::string> function;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
