// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'PlayWithURL'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PlayWithURL — generated read-side data type.
/// schema.json $defs schema 'PlayWithURL'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PlayWithURL {
  std::optional<json> auto_answer;
  std::optional<json> volume;
  std::optional<std::string> say_voice;
  std::optional<std::string> say_language;
  std::optional<std::string> say_gender;
  std::optional<std::string> status_url;
  std::optional<json> url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
