// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'PomSectionBulletsContent'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PomSectionBulletsContent — generated read-side data type.
/// schema.json $defs schema 'PomSectionBulletsContent'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PomSectionBulletsContent {
  std::optional<std::string> title;
  std::optional<json> subsections;
  std::optional<json> numbered;
  std::optional<json> numberedBullets;
  std::optional<std::string> body;
  std::optional<json> bullets;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
