// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'PromptConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PromptConfig — generated read-side data type.
/// schema.json $defs schema 'PromptConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PromptConfig {
  std::optional<json> digit_timeout;
  std::optional<json> initial_timeout;
  std::optional<json> max_digits;
  std::optional<json> play;
  std::optional<json> say_gender;
  std::optional<json> say_language;
  std::optional<json> say_voice;
  std::optional<json> speech_end_timeout;
  std::optional<json> speech_engine;
  std::optional<json> speech_hints;
  std::optional<json> speech_language;
  std::optional<json> speech_timeout;
  std::optional<json> status_url;
  std::optional<json> terminators;
  std::optional<std::string> url;
  std::optional<json> volume;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
