// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// flattened SWMLMethod verb 'prompt' config.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// PromptConfig — generated read-side data type.
/// flattened SWMLMethod verb 'prompt' config.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct PromptConfig {
  std::optional<json> play;
  std::optional<double> volume;
  std::optional<std::string> say_voice;
  std::optional<std::string> say_language;
  std::optional<std::string> say_gender;
  std::optional<json> max_digits;
  std::optional<std::string> terminators;
  std::optional<json> digit_timeout;
  std::optional<json> initial_timeout;
  std::optional<json> speech_timeout;
  std::optional<json> speech_end_timeout;
  std::optional<std::string> speech_language;
  std::optional<json> speech_hints;
  std::optional<std::string> speech_engine;
  std::optional<std::string> status_url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
