// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'RecordConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// RecordConfig — generated read-side data type.
/// schema.json $defs schema 'RecordConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct RecordConfig {
  std::optional<json> format;
  std::optional<json> beep;
  std::optional<json> direction;
  std::optional<json> end_silence_timeout;
  std::optional<json> initial_timeout;
  std::optional<json> input_sensitivity;
  std::optional<json> max_length;
  std::optional<json> status_url;
  std::optional<json> stereo;
  std::optional<json> terminators;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
