// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// flattened SWMLMethod verb 'record_call' config.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// RecordCallConfig — generated read-side data type.
/// flattened SWMLMethod verb 'record_call' config.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct RecordCallConfig {
  std::optional<std::string> control_id;
  std::optional<json> stereo;
  std::optional<json> format;
  std::optional<json> direction;
  std::optional<std::string> terminators;
  std::optional<json> beep;
  std::optional<json> input_sensitivity;
  std::optional<json> initial_timeout;
  std::optional<json> end_silence_timeout;
  std::optional<json> max_length;
  std::optional<std::string> status_url;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
