// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// flattened SWMLMethod verb 'request' config.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// RequestConfig — generated read-side data type.
/// flattened SWMLMethod verb 'request' config.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct RequestConfig {
  std::optional<std::string> url;
  std::optional<json> method;
  std::optional<json> headers;
  std::optional<json> body;
  std::optional<json> timeout;
  std::optional<json> connect_timeout;
  std::optional<json> save_variables;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
