// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'SendSmsConfig'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// SendSmsConfig — generated read-side data type.
/// schema.json $defs schema 'SendSmsConfig'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SendSmsConfig {
  std::optional<json> body;
  std::optional<json> from_number;
  std::optional<json> media;
  std::optional<json> region;
  std::optional<json> status_callback;
  std::optional<json> tags;
  std::optional<json> to_number;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
