// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'SMSWithMedia'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// SMSWithMedia — generated read-side data type.
/// schema.json $defs schema 'SMSWithMedia'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SMSWithMedia {
  std::optional<std::string> to_number;
  std::optional<std::string> from_number;
  std::optional<std::string> region;
  std::optional<json> tags;
  std::optional<json> media;
  std::optional<std::string> body;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
