// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'StartUpHookSWAIGFunction'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// StartUpHookSWAIGFunction — generated read-side data type.
/// schema.json $defs schema 'StartUpHookSWAIGFunction'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct StartUpHookSWAIGFunction {
  std::optional<std::string> description;
  std::optional<std::string> purpose;
  std::optional<json> parameters;
  std::optional<json> fillers;
  std::optional<json> argument;
  std::optional<json> active;
  std::optional<json> meta_data;
  std::optional<std::string> meta_data_token;
  std::optional<json> data_map;
  std::optional<json> skip_fillers;
  std::optional<std::string> web_hook_url;
  std::optional<std::string> wait_file;
  std::optional<json> wait_file_loops;
  std::optional<json> wait_for_fillers;
  std::optional<std::string> function;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
