// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'Step'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// Step — generated read-side data type.
/// schema.json $defs schema 'Step'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct Step {
  std::optional<json> end;
  std::optional<json> functions;
  std::optional<json> gather_info;
  std::optional<std::string> history;
  std::optional<std::string> name;
  std::optional<json> pom;
  std::optional<json> reset;
  std::optional<json> skip_to_next_step;
  std::optional<json> skip_user_turn;
  std::optional<std::string> step_criteria;
  std::optional<std::string> text;
  std::optional<json> valid_contexts;
  std::optional<json> valid_steps;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
