// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// flattened SWMLMethod verb 'user_event' config.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// UserEventConfig — generated read-side data type.
/// flattened SWMLMethod verb 'user_event' config.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct UserEventConfig {
  std::optional<json> event;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
