// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// schema.json $defs schema 'Webhook'.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swml_verbs_generated {

using json = nlohmann::json;

/// Webhook — generated read-side data type.
/// schema.json $defs schema 'Webhook'.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct Webhook {
  std::optional<json> expressions;
  std::optional<json> error_keys;
  std::optional<std::string> url;
  std::optional<json> foreach;
  std::optional<json> headers;
  std::optional<json> method;
  std::optional<json> input_args_as_params;
  std::optional<json> params;
  std::optional<json> require_args;
  std::optional<json> output;
  json extras = json::object();
};

}  // namespace swml_verbs_generated
}  // namespace core
}  // namespace signalwire
