#!/usr/bin/env python3
# Copyright (c) 2025 SignalWire
# SPDX-License-Identifier: MIT
"""Generate the C++ full-mock REST wire-test suite (item E).

Per REST_TEST_GENERATOR_RULES.md. C++ has no reflection, so the route "plan"
(the SDK method to call + the wire (method, path) it produces) is captured from
the REAL generated client by the ``route_registry`` binary (tools/route_registry.cpp,
the CALL() macro). That plan is the INDEPENDENT capture side. The assertion
oracle — the ``matched_route`` each route resolves to — comes from a DIFFERENT
source: the OpenAPI ``operationId`` via the mock server's own SpecLoader, joined
to the plan by (METHOD, normalized-path) with longest-template-wins. Because the
mock and the test both derive ``matched_route`` from the spec, they agree by
construction; a real SDK-vs-spec drift is caught by the separate SPEC-PARITY gate.

Output: one ``tests/test_rest_generated_<ns>.cpp`` per spec namespace, each with,
per implemented route, a SUCCESS test (call the real client vs the shared mock,
assert the journaled (method, matched_route, 2xx)) and an ERROR test (stage a
4xx, assert SignalWireRestError with that status + the same matched_route). The
files are checked in and GEN-FRESH-gated: re-running must be byte-identical.

Usage:
    python3 scripts/generate_rest_tests.py [--check] [--registry-json PATH]

  (no args)          build route_registry, run it, regenerate the test files
  --registry-json P  use an existing plan JSON instead of building/running
  --check            regenerate to a temp dir and diff against the checked-in
                     files; non-zero exit if they differ (GEN-FRESH-TESTS)
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
PORT_ROOT = HERE.parent
PSDK = (PORT_ROOT.parent / "porting-sdk").resolve()
if not PSDK.is_dir():
    PSDK = Path("/usr/local/home/devuser/src/porting-sdk")

# Import the mock's own spec loader so our matched_route resolution is identical
# to what the mock journals at runtime.
sys.path.insert(0, str(PSDK / "test_harness" / "mock_signalwire"))
from mock_signalwire.specs import SpecLoader  # type: ignore  # noqa: E402

TESTS_DIR = PORT_ROOT / "tests"
GEN_PREFIX = "test_rest_generated_"

# The path-parameter sentinel route_registry emits ({id}); substitute a concrete
# segment for spec matching.
CONCRETE = "X"


def build_and_run_registry() -> dict:
    """Build route_registry, run it, return the parsed plan JSON."""
    build = PORT_ROOT / "build"
    subprocess.run(
        ["cmake", "--build", str(build), "--target", "route_registry", "-j", "8"],
        check=True, stdout=subprocess.DEVNULL,
    )
    out = subprocess.run(
        [str(build / "route_registry")], check=True, capture_output=True, text=True
    )
    return json.loads(out.stdout)


def load_spec_routes() -> list:
    """The mock's flat route table: RouteEntry list with .match()/.endpoint_id."""
    return SpecLoader(spec_root=PSDK / "rest-apis").load_all().routes


def resolve_matched_route(method: str, path_template: str, routes: list) -> tuple[str, str] | None:
    """Return (spec_name, endpoint_id) the mock would journal for this dispatch.

    Mirrors the mock: substitute {id}->CONCRETE, match against every spec route
    of the same method, pick the LONGEST template (most specific) on collision.
    """
    concrete = path_template.replace("{id}", CONCRETE)
    candidates = [
        r for r in routes
        if r.method == method.upper() and r.match(concrete) is not None
    ]
    if not candidates:
        return None
    best = max(candidates, key=lambda r: len(r.path_template))
    return best.spec_name, best.endpoint_id


def slug(via: str) -> str:
    """Deterministic test-method slug from the via accessor path."""
    return re.sub(r"[^a-z0-9]+", "_", via.lower()).strip("_")


HEADER = """// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by scripts/generate_rest_tests.py; DO NOT EDIT.
// Regenerate with:  python3 scripts/generate_rest_tests.py
//
// Full-mock REST wire-tests for the '{ns}' namespace (item E). One SUCCESS +
// one ERROR test per implemented canonical route. The call literal is captured
// verbatim from the real generated client by tools/route_registry.cpp; the
// asserted matched_route is the OpenAPI operationId resolved by the mock's own
// SpecLoader — an oracle INDEPENDENT of the resource generator. Included by
// tests/test_main.cpp.
#include "mocktest.hpp"

namespace {{
using namespace signalwire::rest;
using nlohmann::json;
}}  // namespace
"""

SUCCESS_TMPL = """
TEST({test_name}) {{
  auto client = mocktest::make_client();
  mocktest::scenario_set("{endpoint}", 200, json::object());
  (void)({call});
  {{
    auto j = mocktest::journal_last();
    ASSERT_EQ(j.method, std::string("{method}"));
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("{endpoint}"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_TRUE(*j.response_status >= 200 && *j.response_status < 300);
  }}
  return true;
}}
"""

ERROR_TMPL = """
TEST({test_name}) {{
  auto client = mocktest::make_client();
  mocktest::scenario_set("{endpoint}", 500, json{{{{"error", "x"}}}});
  bool threw = false;
  int status = 0;
  try {{
    (void)({call});
  }} catch (const SignalWireRestError& e) {{
    threw = true;
    status = e.status();
  }}
  ASSERT_TRUE(threw);
  ASSERT_EQ(status, 500);
  {{
    auto j = mocktest::journal_last();
    ASSERT_TRUE(j.matched_route.has_value());
    ASSERT_EQ(*j.matched_route, std::string("{endpoint}"));
    ASSERT_TRUE(j.response_status.has_value());
    ASSERT_EQ(*j.response_status, 500);
  }}
  return true;
}}
"""


def rewrite_call(call: str) -> str:
    """Rewrite the registry's ``c.<...>`` call onto the test's ``client`` and
    replace the SENTINEL/id/body/q locals with test literals.

    route_registry writes calls like ``c.fabric().tokens.createEmbedToken({.token = SENTINEL})``
    using locals ``id``/``body``/``q``/``SENTINEL``. In the test file the client
    is named ``client`` and there are no such locals, so substitute literals.
    """
    s = call
    # receiver: c. -> client. (only the leading receiver token)
    if s.startswith("c."):
        s = "client." + s[2:]
    # Substitute the registry's locals with test literals. A negative lookbehind
    # on '.' protects a struct designator field that happens to share the name
    # (e.g. ``{.id = SENTINEL}`` — the ``.id`` field must NOT be rewritten).
    s = re.sub(r"\bSENTINEL\b", '"X"', s)
    s = re.sub(r"(?<!\.)\bid\b", '"X"', s)
    s = re.sub(r"(?<!\.)\bbody\b", "json::object()", s)
    s = re.sub(r"(?<!\.)\bq\b", "std::map<std::string, std::string>{}", s)
    return s


def generate(plan: dict, routes: list) -> dict[str, str]:
    """Return {filename: file-contents} for every namespace test file."""
    # group plan routes by resolved spec namespace
    by_ns: dict[str, list] = {}
    unmapped: list = []
    for r in plan["routes"]:
        resolved = resolve_matched_route(r["method"], r["path_template"], routes)
        if resolved is None:
            unmapped.append(r)
            continue
        spec_name, endpoint = resolved
        by_ns.setdefault(spec_name, []).append((r, endpoint))

    if unmapped:
        for r in unmapped:
            print(f"UNMAPPED {r['method']} {r['path_template']} (via {r['via']})", file=sys.stderr)
        raise SystemExit(f"generate_rest_tests: {len(unmapped)} route(s) matched no spec operationId")

    out: dict[str, str] = {}
    for ns in sorted(by_ns):
        # deterministic order: by (method, path, via)
        entries = sorted(by_ns[ns], key=lambda e: (e[0]["method"], e[0]["path_template"], e[0]["via"]))
        parts = [HEADER.format(ns=ns)]
        for r, endpoint in entries:
            call = rewrite_call(r["call"])
            # The 'rest_mock_' prefix is load-bearing: the REST-COVERAGE gate
            # selects tests by that substring, and the parallel runner treats
            # that prefix as session-isolated (make_client's random-project auth
            # scope). Keep it.
            base = f"rest_mock_gen_{slug(r['via'])}"
            parts.append(SUCCESS_TMPL.format(
                test_name=f"{base}_ok", endpoint=endpoint, call=call, method=r["method"]))
            parts.append(ERROR_TMPL.format(
                test_name=f"{base}_err", endpoint=endpoint, call=call))
        fname = f"{GEN_PREFIX}{ns.replace('-', '_')}.cpp"
        out[fname] = "".join(parts)
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--registry-json", type=Path, default=None)
    ap.add_argument("--check", action="store_true",
                    help="regenerate + diff vs checked-in files (GEN-FRESH-TESTS)")
    args = ap.parse_args(argv)

    if args.registry_json:
        plan = json.loads(args.registry_json.read_text())
    else:
        plan = build_and_run_registry()

    routes = load_spec_routes()
    files = generate(plan, routes)

    if args.check:
        stale = []
        for fname, content in files.items():
            existing = (TESTS_DIR / fname).read_text() if (TESTS_DIR / fname).exists() else None
            if existing != content:
                stale.append(fname)
        # also flag any checked-in generated file the generator no longer emits
        for p in TESTS_DIR.glob(f"{GEN_PREFIX}*.cpp"):
            if p.name not in files:
                stale.append(p.name + " (orphan)")
        if stale:
            print("GEN-FRESH-TESTS: generated REST test files are STALE:", file=sys.stderr)
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            print("  run: python3 scripts/generate_rest_tests.py", file=sys.stderr)
            return 1
        print(f"GEN-FRESH-TESTS: {len(files)} generated REST test file(s) up to date.")
        return 0

    for fname, content in files.items():
        (TESTS_DIR / fname).write_text(content)
    print(f"generate_rest_tests: wrote {len(files)} file(s), {len(plan['routes'])} routes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
