// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// swaig-request `SwaigRequest` schema.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swaig_request_generated {

using json = nlohmann::json;

/// SwaigRequest — generated read-side data type.
/// swaig-request `SwaigRequest` schema.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SwaigRequest {
  std::optional<std::string> ai_session_id;
  std::optional<std::string> app_name;
  std::optional<std::string> args;
  std::optional<json> argument;
  std::optional<json> argument_desc;
  std::optional<std::string> call_id;
  std::optional<json> call_log;
  std::optional<std::string> caller_id_name;
  std::optional<std::string> caller_id_num;
  std::optional<bool> channel_active;
  std::optional<bool> channel_offhook;
  std::optional<bool> channel_ready;
  std::optional<json> content_disposition;
  std::optional<json> content_type;
  std::optional<std::string> conversation_id;
  std::optional<std::string> description;
  std::optional<std::string> error_reason;
  std::optional<bool> fatal_error;
  std::optional<std::string> function;
  std::optional<json> global_data;
  std::optional<std::string> input;
  std::optional<json> meta_data;
  std::optional<std::string> meta_data_token;
  std::optional<std::string> project_id;
  std::optional<json> raw_call_log;
  std::optional<std::string> space_id;
  std::optional<json> version;
  json extras = json::object();
};

}  // namespace swaig_request_generated
}  // namespace core
}  // namespace signalwire
