// Copyright (c) 2025 SignalWire
// SPDX-License-Identifier: MIT
//
// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// inline swaig-request `argument` object.
#pragma once

#include <map>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace signalwire {
namespace core {
namespace swaig_request_generated {

using json = nlohmann::json;

/// SwaigArgument — generated read-side data type.
/// inline swaig-request `argument` object.
///
/// Method-less DTO: one typed member per snake wire key + open `extras`.
struct SwaigArgument {
  std::optional<json> parsed;
  std::optional<std::string> raw;
  std::optional<std::string> substituted;
  json extras = json::object();
};

}  // namespace swaig_request_generated
}  // namespace core
}  // namespace signalwire
